### ISSUE TITLE
Misspellings

### ISSUE THREAD

**Issue by Konstantin-Glukhov** [Pomax/nrGrammar#13]
In section 2.3.2 - Inflection the following table shows spelling でしよ for 未然形 of です:

                 です	だ	copula
未然形	でしよ	だろ	だろ
連用形	でし	         だっ (で)	で
終止形	です	        だ	です/だ
連体形	です	        な	です/な
已然形		        なら	なら

According to http://dictionary.goo.ne.jp/jn/151501/meaning/m1u/%E3%81%A7%E3%81%99/
it should be でしょ

**Comment by Pomax** [comment]
well spotted! that should absolutely be でしょ -- fixed.

**Comment by Konstantin-Glukhov** [comment]
Hi Michiel,
Thank you for correcting the typo.
A search for でしよ yields three more hits of the same typo. I should have mentioned it on the first place.

**Comment by Pomax** [comment]
@Konstantin-Glukhov I think the subsequent PRs resolved this issue, but just to be sure: can we close this one?

**Comment by Konstantin-Glukhov** [comment]
The issue has been resolved.
