### ISSUE TITLE
Website down (misconfiguration?)

### ISSUE THREAD

**Issue by qsantos** [Pomax/nrGrammar#27]
Hello,

it seems that the [online book](https://pomax.github.io/nrGrammar/) is done, and the URL is interpreted as part of the parent blog (I get a “Post redirection” message).

**Comment by RyanBreaker** [comment]
Same, I can't find a workaround either or a post on the blog for a real link.

His blog's main page's header has a link to [here](http://www.nihongoresources.com/dictionaries/universal.html) which has a PDF which I'm not sure is the free eBook this project is about: http://www.nihongoresources.com/media/An%20introduction%20to%20Japanese%20-%20Syntax,%20Grammar%20&%20Language.pdf

**Comment by Pomax** [comment]
Okay, apparently github decided to forget its gh-pages binding.
