### ISSUE TITLE
Shouldn't 試験 has furigana しけん instead of しかん

### ISSUE THREAD

**Issue by mmargoliono** [Pomax/nrGrammar#37]
On section "4.2.4.8 のみ — Nothing but", one of the example containing the word 試験, but the furigana says しかん　instead of しけん

**Comment by Pomax** [comment]
it should, well spotted!

**Comment by Pomax** [comment]
![image](https://user-images.githubusercontent.com/177243/56913516-b22cce00-6a66-11e9-834c-aadae1fbbbbc.png)
