### ISSUE TITLE
A bit dissapointed after reaching chapter 2

### ISSUE THREAD

**Issue by quetzalsly** [Pomax/nrGrammar#39]
A lot of my friends were linking me the guide and after I finished chapter 1 I thought wow this is the best overview of Japanese ever. The author truly understands all the differences between the languages and gives a brief history of how kanji evolved etc. However after reaching chapter 2 it became completly unreadable for me... it went from a thing an average person could read and understand in simple terms, to a scientific journal for PHD linguistics students. I appreciate the fact that everything is so in depth but its just impossible for me to read without my brain starting to hurt, I don't know all the fancy words like inflection... I am not a linguistics student, I am just a normal dude trying to understand Japanese.

Another thing that was mind boggling for me is that the guide went from using romaji and then the next chapter completly switching to complex kanji without furigana! Why is it so hard to just keep the romaji and furigana? You have to realise not everyone has the same learning process, not everyone learns kanji first, some people only learn kanji in order of JLPT levels, some learn all 3000 at once, some like me leave that until later. I started with core 10k vocab + grammar + watching tv shows / anime in between. So far I got by reading furigana just fine and plan to start kanji studies several months later.

I don't know why I made this issue because I doubt you would be willing to change the guide, the ideal guide I can picture in my head would have two sections or even two separate guides, an easy to read overview with charts showing all the particles and rules in one place, kinda like a quick reference guide and then the other part being the very in depth version explaining everything.

Anyway this is just a perspective of someone starting out and finding your guide, I just wanted you to see things from a different perspective, please close this issue if you want.

**Comment by Pomax** [comment]
The textbook was written for an audience that needs an alternative to an expensive university course. If you just want to casually learn Japanese, then this book (and books like it) are not the right resource to do that with.

As for the lack of furigana, I'm scrolling through http://pomax.github.io/nrGrammar/#section-2-Verb_grammar right now, and there is plenty of furigana, which browser are you using and/or are you running any script blockers or userstyles extensions that might be blocking the markup?

E.g:

![image](https://user-images.githubusercontent.com/177243/92263479-8a871a80-ee91-11ea-908d-152f7ee2d8bc.png)

And:

![image](https://user-images.githubusercontent.com/177243/92263501-94a91900-ee91-11ea-9df7-ab93b9eed85f.png)

All have furigana.

**Comment by reedleoneil** [comment]
After I finished reading casual books and guides I was looking for another guide that leads me here and after reading chapter 1, it started to make sense and I think this would definitely be one of the best overview of Japanese ever. I especially appreciate Section 1-4 Word and word classes & Section 1-5 Sentence structure which you can't find in some of the casual books. After reaching chapter 2, something started to make sense again regarding verbs and verbal adjectives (which I believe are called い-adjectives on casual books). As for the fancy word inflection, that section made me realize why they were called 五段 verbs and 一段 verbs (ru-verbs & u-verbs or type 1 & type 2 in other books). I am trying to understand Japanese better to get a full grasp of the "not so fancy rules" from traditional learning materials.

@quetzalsly I do understand that not everyone has the same learning process, I do started learning Japanese without 漢字 (kanji) and I regretted it. I wish I had started learning kanji right away from the start. Learning vocabulary is much easier by learning kanji. I don't know how you have learned the core 10k vocab but let's be real, learning kanji is necessary. And a friendly tip, don't rely too much on romaji, and if possible don't use it.

After reading several casual books and guides, I think this book will let me see Japanese language in another perspective different from traditional learning materials. Happy learning 😄
