### ISSUE TITLE
"Arabian" in section 1.4.11 should be "Arabic"

### ISSUE THREAD

**Issue by chyza** [Pomax/nrGrammar#40]
"Arabian" is an adjective relating to the Arabian peninsula, while Arabic is the language, since it was in a big list of languages I assume the latter was intended.

**Comment by Pomax** [comment]
Cheers. For future reference, github lets you submit typo corrections directly through the site. Just go to the file you found the error on, then click the pencil icon:

![image](https://user-images.githubusercontent.com/177243/112761865-14bfd900-8fb2-11eb-8171-b5f338783f1c.png)

This will let you change the text and send that off to project maintainers as a PR without every having to go through the crazy "cloning a repo in the terminal, editing files in a code editor, forming a PR, pushing that up" etc. etc. nonsense =)

**Comment by Pomax** [comment]
https://github.com/Pomax/nrGrammar/commit/4acf8ef8ea41eaa07469d5a8eb918f1e21b08eea
