### ISSUE TITLE
Small issue about て-form of 軋む

### ISSUE THREAD

**Issue by benjamin20104** [Pomax/nrGrammar#44]
In section 3.2.3.1, the example sentence そのドアがよく軋っています seems to suggest that the て-form of 軋む is 軋って, whereas it is in fact 軋んで. I could be mistaken as I am a beginner.

**Comment by Pomax** [comment]
The て-form of 軋む is indeed 軋んで, but that's not the verb we're using here. We're using the godan 軋る.
