### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Kreijstal** [Pomax/nrGrammar#45]
I've always been fascinated by "open source" books, not in the sense that I want to steal their contents, but in the sense oh cool their infrastructure is open, (so if you wanted to start making your own book, you would have a template to start) Since most books that are ever published, you have absolutely no idea, how are they made? Which software do they use? Do they use TeX? or propietary technologies?

I know this is not code, but a license would be nice to have even if not open source, source available, what not.

**Comment by Pomax** [comment]
It would be, but instead there won't be one, and you're simply going to have to ask whether you can have permission do the specific thing you want to do, in order to make sure that dialog happens =)
